### ISSUE TITLE
bug in src/examples/Tutorial/main1.py line 162

### ISSUE THREAD

**Issue by chenrq2005** [acsicuib/YAFS#58]
Traceback (most recent call last):
  File "src/examples/Tutorial/main1.py", line 162, in <module>
    logging.config.fileConfig(os.getcwd()+'/logging.ini')
  File "/Users/chenru4/opt/anaconda3/envs/edgeai/lib/python3.7/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/Users/chenru4/opt/anaconda3/envs/edgeai/lib/python3.7/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/Users/chenru4/opt/anaconda3/envs/edgeai/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

**Comment by wisaaco** [comment]
update and improved the project and doc to run the examples.
